#!/usr/bin/env bash
set -eu
set -f

ROOT="$(cd "$(dirname "$0")/.." && pwd -P)"
REPO_ROOT="$(cd "$ROOT/../.." && pwd -P)"
SKILL="$ROOT/SKILL.md"
RUNNER="$REPO_ROOT/skills/e2e-runner/SKILL.md"
CONTRACT="$ROOT/reference/e2e-scenario-contract.md"
VALIDATOR="$ROOT/scripts/validate-catalog.js"
DISCOVER="$ROOT/scripts/discover-surfaces.js"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/vulpora-e2e-author.XXXXXX")" || exit 1
trap 'rm -rf "$WORK"' EXIT HUP INT TERM

test -s "$CONTRACT"
test -x "$VALIDATOR"
test -x "$DISCOVER"
grep -Fq 'skill | e2e-runner | skills/e2e-runner | - | e2e-scenario-author | -' "$REPO_ROOT/install/manifest.txt"
grep -Fq 'skill | e2e-report-renderer | skills/e2e-report-renderer | - | e2e-scenario-author | -' "$REPO_ROOT/install/manifest.txt"

for required in \
  'reference/e2e-scenario-contract.md' \
  'scripts/discover-surfaces.js' \
  'Detect the repository profile before enumerating surfaces' \
  'exactly one primary executable fence' \
  'one optional `shell` teardown fence' \
  'atomically replace' \
  'VALIDATION-FAIL-SIZE-MIN' \
  'Source fingerprint: sha256' \
  'SCA-19 (Source inventory coverage)'; do
  grep -Fq "$required" "$SKILL"
done

if grep -Fq 'writes **exactly two paths**' "$SKILL"; then
  echo 'stale two-path claim remains' >&2
  exit 1
fi
if grep -Fq 'last in their `AREA`' "$SKILL"; then
  echo 'stale last-in-area cleanup exception remains' >&2
  exit 1
fi
if grep -Fq '.slug-map.txt' "$SKILL" || grep -Fq 'app-api/src/main' "$SKILL" || grep -Fq 'app-worker/src/main' "$SKILL"; then
  echo 'stale sidecar or hardcoded module path remains' >&2
  exit 1
fi
grep -Fq 'RUN-7.0 (One environment owner)' "$RUNNER"
grep -Fq '**Catalog harness:**' "$RUNNER"
grep -Fq 'Spring Boot or NestJS modules' "$RUNNER"
grep -Fq 'validate-catalog.js <catalog> <contract> <inventory>' "$RUNNER"
if grep -Fq 'For each of `app-api`' "$RUNNER" || grep -Fq 'port `18082`' "$RUNNER"; then
  echo 'runner still hardcodes application modules or ports' >&2
  exit 1
fi

cat > "$WORK/valid.md" <<'MARKDOWN'
<!-- AUTO-GENERATED by e2e-scenario-author. DO NOT EDIT. Human notes belong in docs/e2e-scenarios/notes.md. -->
<!-- Source fingerprint: sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -->
<!-- Contract: docs/e2e-scenarios/CONTRACT.md version 1 -->

# E2E Scenario Catalog

### `E2E-ARTICLE-GET-HAPPY` — 목록 조회는 성공한다

| Field | Value |
|---|---|
| Target | `GET /api/v1/articles` (app-api) |
| Purpose | 합성 사용자로 목록 조회 성공을 확인한다 |
| Preconditions | `service.app-api.ready == true` |
| Dataset | `userId=100, size=20` |
| Expected | `200 OK`; `$.content` present |
| Mutates | — |
| Depends-on | — |
| Captures | — |
| Notes | — |

```http
GET {{api}}/api/v1/articles?userId=100&size=20
```

### `E2E-ORDER-POST-HAPPY` — 주문 생성은 성공하고 정리된다

| Field | Value |
|---|---|
| Target | `POST /api/v1/orders` (app-api) |
| Purpose | 합성 회원으로 주문 생성 성공을 확인한다 |
| Preconditions | `service.app-api.ready == true` |
| Dataset | `memberId=900, productId=100` |
| Expected | `201 Created`; `$.id` present |
| Mutates | `orders` |
| Depends-on | — |
| Captures | ORDER-ID |
| Notes | primary 결과와 무관하게 teardown으로 생성 주문을 정리한다 |

```http
POST {{api}}/api/v1/orders
Content-Type: application/json

{"memberId":900,"productId":100}

```

```shell
# teardown
curl -fsS -X DELETE "{{api}}/api/v1/orders/{{ORDER-ID}}"
```
MARKDOWN

node "$VALIDATOR" "$WORK/valid.md" "$CONTRACT" >/dev/null

awk 'BEGIN{seen=0} {print} /^```$/ && ++seen==1 {print "\n```shell\necho forbidden-second-fence\n```"}' \
  "$WORK/valid.md" > "$WORK/two-fences.md"
if node "$VALIDATOR" "$WORK/two-fences.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'multiple executable fences were accepted' >&2
  exit 1
fi

awk 'BEGIN{fences=0;skip=0} /^```shell$/ {fences++; if(fences==1){skip=1; next}} skip && /^```$/ {skip=0; next} !skip {print}' \
  "$WORK/valid.md" > "$WORK/missing-teardown.md"
if node "$VALIDATOR" "$WORK/missing-teardown.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'mutating scenario without teardown was accepted' >&2
  exit 1
fi
sed 's/| Mutates | `orders` |/| Mutates | — |/' "$WORK/missing-teardown.md" > "$WORK/undeclared-mutation.md"
if node "$VALIDATOR" "$WORK/undeclared-mutation.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'state-changing HTTP without Mutates was accepted' >&2
  exit 1
fi

node - "$WORK/valid.md" "$WORK/chained-teardown.md" "$WORK/unrelated-teardown.md" "$WORK/mutating-sql.md" "$WORK/chained-primary.md" <<'NODE'
const fs=require('node:fs');const [src,chained,unrelated,sql,primary]=process.argv.slice(2),value=fs.readFileSync(src,'utf8');
fs.writeFileSync(chained,value.replace(
  'curl -fsS -X DELETE "{{api}}/api/v1/orders/{{ORDER-ID}}"',
  'curl -fsS -X DELETE "{{api}}/api/v1/orders/{{ORDER-ID}}" && curl -fsS "{{api}}/actuator/health"'));
fs.writeFileSync(unrelated,value.replace(
  'curl -fsS -X DELETE "{{api}}/api/v1/orders/{{ORDER-ID}}"',
  'curl -fsS -X DELETE "{{api}}/cleanup/{{UNRELATED-ID}}"'));
fs.writeFileSync(sql,value.replace(
  '```http\nGET {{api}}/api/v1/articles?userId=100&size=20\n```',
  '```sql\nWITH removed AS (DELETE FROM articles RETURNING *) SELECT * FROM removed\n```'));
fs.writeFileSync(primary,value.replace(
  '```http\nGET {{api}}/api/v1/articles?userId=100&size=20\n```',
  '```shell\ncurl -fsS "{{api}}/api/v1/articles" | sh\n```'));
NODE
if node "$VALIDATOR" "$WORK/chained-teardown.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'chained teardown command was accepted' >&2
  exit 1
fi
if node "$VALIDATOR" "$WORK/unrelated-teardown.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'teardown unrelated to declared mutation was accepted' >&2
  exit 1
fi
if node "$VALIDATOR" "$WORK/mutating-sql.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'mutating SQL CTE was accepted' >&2
  exit 1
fi
if node "$VALIDATOR" "$WORK/chained-primary.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'chained primary shell command was accepted' >&2
  exit 1
fi

sed 's/| Depends-on | — |/| Depends-on | E2E-MISSING |/' "$WORK/valid.md" > "$WORK/bad-dependency.md"
if node "$VALIDATOR" "$WORK/bad-dependency.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'singular or missing dependency was accepted' >&2
  exit 1
fi

sed 's#`GET /api/v1/articles` (app-api)#article list endpoint#' "$WORK/valid.md" > "$WORK/bad-target.md"
if node "$VALIDATOR" "$WORK/bad-target.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'free-form target was accepted' >&2
  exit 1
fi

sed 's/E2E-ORDER-POST-HAPPY/E2E-ARTICLE-GET-HAPPY/g' "$WORK/valid.md" > "$WORK/duplicate.md"
if node "$VALIDATOR" "$WORK/duplicate.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'duplicate scenario id was accepted' >&2
  exit 1
fi

node - "$WORK/valid.md" "$WORK/cycle.md" <<'NODE'
const fs=require('node:fs');let value=fs.readFileSync(process.argv[2],'utf8'),seen=0;
value=value.replace('| Depends-on | — |',()=>{seen++;return '| Depends-on | [E2E-ORDER-POST-HAPPY] |';});
value=value.replace('| Depends-on | — |',()=>{seen++;return '| Depends-on | [E2E-ARTICLE-GET-HAPPY] |';});
fs.writeFileSync(process.argv[3],value);
NODE
if node "$VALIDATOR" "$WORK/cycle.md" "$CONTRACT" >/dev/null 2>&1; then
  echo 'dependency cycle was accepted' >&2
  exit 1
fi

mkdir -p "$WORK/spring-repo/app/src/main/kotlin/demo" "$WORK/spring-repo/app/src/main/resources"
cat > "$WORK/spring-repo/settings.gradle.kts" <<'GRADLE'
include("app")
GRADLE
cat > "$WORK/spring-repo/app/build.gradle.kts" <<'GRADLE'
plugins { id("org.springframework.boot") version "3.5.0" }
dependencies { implementation("org.springframework.boot:spring-boot-starter-web") }
GRADLE
cat > "$WORK/spring-repo/app/src/main/kotlin/demo/ArticleController.kt" <<'KOTLIN'
package demo

import jakarta.validation.Valid
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RestController

@RestController
@RequestMapping("\${api.articles.path}")
class ArticleController {
    @GetMapping(ApiPaths.LIST)
    fun list(): List<String> = emptyList()

    @PostMapping
    fun create(@Valid @RequestBody request: CreateArticleRequest): String = request.name
}
KOTLIN
cat > "$WORK/spring-repo/app/src/main/kotlin/demo/ApiPaths.kt" <<'KOTLIN'
package demo

object ApiPaths {
    const val LIST = ""
}
KOTLIN
cat > "$WORK/spring-repo/app/src/main/kotlin/demo/CreateArticleRequest.kt" <<'KOTLIN'
package demo

import jakarta.validation.constraints.NotBlank

data class CreateArticleRequest(
    @field:NotBlank val name: String,
)
KOTLIN
cat > "$WORK/spring-repo/app/src/main/resources/application.yml" <<'YAML'
api:
  articles:
    path: /api/v1/articles
YAML

node "$DISCOVER" "$WORK/spring-repo" "$CONTRACT" > "$WORK/inventory.json"
node - "$WORK" "$DISCOVER" "$CONTRACT" <<'NODE'
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {spawnSync} = require('node:child_process');
const [work, discover, contract] = process.argv.slice(2);
const sourceModule = path.join(work, 'spring-repo/app');
function inventory(root, env = process.env) {
  const result = spawnSync(process.execPath, [discover, root, contract], {encoding: 'utf8', env});
  assert.equal(result.status, 0, result.stderr);
  return JSON.parse(result.stdout);
}

// A root-level Spring application has one module, not one per source file.
const rootProject = path.join(work, 'root-spring-repo');
fs.cpSync(sourceModule, rootProject, {recursive: true});
const rootInventory = inventory(rootProject);
assert.equal(rootInventory.profile, 'spring-jvm');
assert.deepEqual(rootInventory.surfaces.map((surface) => surface.module),
  [':', ':']);
assert(rootInventory.surfaces.every((surface) => surface.target.endsWith(' (:)')));
assert.deepEqual(inventory(rootProject), rootInventory, 'inventory must be deterministic');
fs.writeFileSync(path.join(work, 'root-inventory.json'), JSON.stringify(rootInventory));

// Checkout names are not source inputs and must not change target identities.
const relocatedProject = path.join(work, 'relocated checkout');
fs.cpSync(rootProject, relocatedProject, {recursive: true});
assert.deepEqual(inventory(relocatedProject), rootInventory);

// A child named after the checkout is still a separate module from the root.
const childSource = path.join(rootProject, 'root-spring-repo/src/main/java/demo');
fs.mkdirSync(childSource, {recursive: true});
fs.writeFileSync(path.join(childSource, 'ChildController.java'), `
@RestController
class ChildController {
  @GetMapping("/api/v1/articles")
  public String list() { return "ok"; }
}
`);
assert.deepEqual(inventory(rootProject).surfaces.map((surface) => surface.module).sort(),
  [':', ':', 'root-spring-repo']);

// Keep the existing colon-separated identity for nested Gradle/Maven modules.
const nestedProject = path.join(work, 'nested-spring-repo');
fs.cpSync(sourceModule, path.join(nestedProject, 'services/api'), {recursive: true});
assert.deepEqual(inventory(nestedProject).surfaces.map((surface) => surface.module),
  ['services:api', 'services:api']);

// Source bytes, not the host's default collation, determine the inventory.
const localeProject = path.join(work, 'locale-spring-repo');
fs.cpSync(sourceModule, localeProject, {recursive: true});
for (const [language, extension, classPrefix] of [['java', 'java', 'Java'], ['kotlin', 'kt', 'Kotlin']]) {
  const directory = path.join(localeProject, 'src/main', language, 'demo');
  fs.mkdirSync(directory, {recursive: true});
  for (const [filename, className, route] of [
    ['ÄController', 'AController', `/locale/${language}/ä`],
    ['ZController', 'ZController', `/locale/${language}/z`],
  ]) {
    const method = language === 'java'
      ? 'public String get() { return "ok"; }'
      : 'fun get(): String = "ok"';
    fs.writeFileSync(path.join(directory, `${filename}.${extension}`),
      `@RestController\nclass ${classPrefix}${className} {\n  @GetMapping("${route}")\n  ${method}\n}\n`);
  }
}
const localeInventories = [];
for (const [requested, expected] of [
  ['en_US.UTF-8', 'en-US'], ['sv_SE.UTF-8', 'sv-SE'], ['ko_KR.UTF-8', 'ko-KR'],
]) {
  const env = {...process.env, LANG: requested, LC_ALL: requested};
  const probe = spawnSync(process.execPath,
    ['-e', 'process.stdout.write(Intl.Collator().resolvedOptions().locale)'], {encoding: 'utf8', env});
  assert.equal(probe.status, 0, `Intl locale probe failed for ${requested}: ${probe.stderr}`);
  assert.equal(probe.stdout, expected,
    `locale regression requires actual ${expected} collation, not a fallback: ${probe.stdout}`);
  localeInventories.push(inventory(localeProject, env));
}
for (const current of localeInventories) {
  assert.deepEqual(current, localeInventories[0], 'inventory must be identical across EN/SV/KO locales');
}
for (const current of localeInventories) {
  assert.deepEqual(current.inputs, [...current.inputs].sort(), 'inputs use explicit code-unit ordering');
  const keys = current.surfaces.map(surface => surface.key);
  assert.deepEqual(keys, [...keys].sort(), 'surface keys use explicit code-unit ordering');
}

// Duplicate endpoints in different root-level files must share the same key.
const controller = path.join(rootProject, 'src/main/kotlin/demo/ArticleController.kt');
fs.writeFileSync(path.join(path.dirname(controller), 'OtherController.kt'),
  fs.readFileSync(controller, 'utf8').replace('class ArticleController', 'class OtherController'));
const duplicate = spawnSync(process.execPath, [discover, rootProject, contract], {encoding: 'utf8'});
assert.notEqual(duplicate.status, 0, 'duplicate root endpoints must be rejected');
assert.match(duplicate.stderr, /SCA-6\.2/);
NODE
inventory_fingerprint="$(node -e 'process.stdout.write(JSON.parse(require("node:fs").readFileSync(process.argv[1],"utf8")).source_fingerprint)' "$WORK/inventory.json")"
cat > "$WORK/inventory-catalog.md" <<'MARKDOWN'
<!-- AUTO-GENERATED by e2e-scenario-author. DO NOT EDIT. Human notes belong in docs/e2e-scenarios/notes.md. -->
<!-- Source fingerprint: sha256:INVENTORY_FINGERPRINT -->
<!-- Contract: docs/e2e-scenarios/CONTRACT.md version 1 -->

# E2E Scenario Catalog

### `E2E-ARTICLE-GET-HAPPY` — 목록 조회는 성공한다

| Field | Value |
|---|---|
| Target | `GET /api/v1/articles` (app) |
| Purpose | 합성 사용자로 목록 조회 성공을 확인한다 |
| Preconditions | `service.app.ready == true` |
| Dataset | `size=20` |
| Expected | `200 OK`; `$.content` present |
| Mutates | — |
| Depends-on | — |
| Captures | — |
| Notes | — |

```http
GET {{api}}/api/v1/articles?size=20
```

### `E2E-ARTICLE-POST-HAPPY` — 게시물 생성은 성공하고 정리된다

| Field | Value |
|---|---|
| Target | `POST /api/v1/articles` (app) |
| Purpose | 합성 이름으로 게시물 생성 성공을 확인한다 |
| Preconditions | `service.app.ready == true` |
| Dataset | `name=synthetic-article` |
| Expected | `201 Created`; `$.id` present |
| Mutates | `articles` |
| Depends-on | — |
| Captures | ARTICLE-ID |
| Notes | primary 결과와 무관하게 생성 게시물을 정리한다 |

```http
POST {{api}}/api/v1/articles
Content-Type: application/json

{"name":"synthetic-article"}

```

```shell
# teardown
curl -fsS -X DELETE "{{api}}/api/v1/articles/{{ARTICLE-ID}}"
```

### `E2E-ARTICLE-POST-VALIDATION-FAIL-NAME-NOT-BLANK` — 빈 이름은 거부된다

| Field | Value |
|---|---|
| Target | `POST /api/v1/articles` (app) |
| Purpose | 이름의 NotBlank 제약을 확인한다 |
| Preconditions | `service.app.ready == true` |
| Dataset | `name=blank` |
| Expected | `400 Bad Request`; `$.errors.name` present |
| Mutates | — |
| Depends-on | — |
| Captures | — |
| Notes | 실패 요청은 상태를 변경하지 않는다 |

```http
POST {{api}}/api/v1/articles
Content-Type: application/json

{"name":""}

```
MARKDOWN
sed "s/INVENTORY_FINGERPRINT/$inventory_fingerprint/" "$WORK/inventory-catalog.md" > "$WORK/inventory-catalog-bound.md"
node "$VALIDATOR" "$WORK/inventory-catalog-bound.md" "$CONTRACT" "$WORK/inventory.json" >/dev/null
node - "$WORK" <<'NODE'
const fs = require('node:fs');
const path = require('node:path');
const work = process.argv[2];
const inventory = JSON.parse(fs.readFileSync(path.join(work, 'root-inventory.json'), 'utf8'));
const catalog = fs.readFileSync(path.join(work, 'inventory-catalog.md'), 'utf8')
  .replace('INVENTORY_FINGERPRINT', inventory.source_fingerprint).replaceAll('(app)', '(:)');
fs.writeFileSync(path.join(work, 'root-catalog.md'), catalog);
NODE
node "$VALIDATOR" "$WORK/root-catalog.md" "$CONTRACT" "$WORK/root-inventory.json" >/dev/null

sed 's/E2E-ARTICLE-POST-VALIDATION-FAIL-NAME-NOT-BLANK/E2E-ARTICLE-POST-BOUNDARY/' \
  "$WORK/inventory-catalog-bound.md" > "$WORK/missing-source-coverage.md"
if node "$VALIDATOR" "$WORK/missing-source-coverage.md" "$CONTRACT" "$WORK/inventory.json" >/dev/null 2>&1; then
  echo 'catalog missing a source-required validation behavior was accepted' >&2
  exit 1
fi

sed 's#GET /api/v1/articles` (app)#GET /api/v1/ghost` (app)#' \
  "$WORK/inventory-catalog-bound.md" > "$WORK/extra-target.md"
if node "$VALIDATOR" "$WORK/extra-target.md" "$CONTRACT" "$WORK/inventory.json" >/dev/null 2>&1; then
  echo 'catalog target absent from source inventory was accepted' >&2
  exit 1
fi

printf '\n// source fingerprint must change\n' >> "$WORK/spring-repo/app/src/main/kotlin/demo/ArticleController.kt"
node "$DISCOVER" "$WORK/spring-repo" "$CONTRACT" > "$WORK/changed-inventory.json"
if node "$VALIDATOR" "$WORK/inventory-catalog-bound.md" "$CONTRACT" "$WORK/changed-inventory.json" >/dev/null 2>&1; then
  echo 'stale catalog fingerprint was accepted' >&2
  exit 1
fi

mkdir -p "$WORK/async-repo/app/src/main/kotlin/demo" "$WORK/async-repo/app/src/main/resources"
cat > "$WORK/async-repo/settings.gradle.kts" <<'GRADLE'
include("app")
GRADLE
cat > "$WORK/async-repo/app/build.gradle.kts" <<'GRADLE'
plugins { id("org.springframework.boot") version "3.5.0" }
dependencies { implementation("org.springframework.kafka:spring-kafka") }
GRADLE
cat > "$WORK/async-repo/app/src/main/kotlin/demo/AsyncSurfaces.kt" <<'KOTLIN'
package demo

import org.springframework.kafka.annotation.KafkaListener
import org.springframework.kafka.annotation.RetryableTopic

class ArticleListener {
    @RetryableTopic
    @KafkaListener(topics = ["\${topics.article}"], groupId = "article-e2e")
    fun consume(value: String) = value
}

class ArticleOutboxHandler(
    private val outboxRepository: Any,
) : OutboxEventHandler<String> {
    fun handle(value: String) = outboxRepository.toString() + value
}

class ArticleOutboxPublisher(
    private val outboxRepository: Any,
) {
    fun publish(value: String) = outboxRepository.toString() + value
}
KOTLIN
cat > "$WORK/async-repo/app/src/main/kotlin/demo/PublicMetaApi.kt" <<'KOTLIN'
package demo

import org.springframework.web.bind.annotation.GetMapping

@GetMapping("/meta")
annotation class PublicMetaApi
KOTLIN
cat > "$WORK/async-repo/app/src/main/kotlin/demo/MetaController.kt" <<'KOTLIN'
package demo

import org.springframework.web.bind.annotation.RestController

@RestController
class MetaController {
    @InternalOnly
    @PublicMetaApi
    fun metadata(): String = "ok"
}
KOTLIN
cat > "$WORK/async-repo/app/src/main/kotlin/demo/InternalOnly.kt" <<'KOTLIN'
package demo

import org.springframework.security.access.prepost.PreAuthorize

@PreAuthorize("hasRole('USER')")
annotation class InternalOnly
KOTLIN
cat > "$WORK/async-repo/app/src/main/resources/application.yml" <<'YAML'
topics:
  article: article.events
YAML
node "$DISCOVER" "$WORK/async-repo" "$CONTRACT" > "$WORK/async-inventory.json"
node - "$WORK/async-inventory.json" <<'NODE'
const inventory=require(process.argv[2]);
const byTarget=new Map(inventory.surfaces.map((surface)=>[surface.target,surface.required_behaviors.join(',')]));
if(byTarget.get('KAFKA article.events (app)')!=='CONSUME,DLQ')process.exit(1);
if(byTarget.get('OUTBOX ArticleOutboxHandler (app)')!=='CONSUME,PUBLISH')process.exit(1);
if(byTarget.get('OUTBOX ArticleOutboxPublisher (app)')!=='PUBLISH')process.exit(1);
if(byTarget.get('GET /meta (app)')!=='AUTH-FAIL,HAPPY')process.exit(1);
NODE

mkdir -p "$WORK/nest-repo/apps/api/src"
cat > "$WORK/nest-repo/package.json" <<'JSON'
{"name":"generic-workspace","private":true,"packageManager":"pnpm@10.0.0"}
JSON
cat > "$WORK/nest-repo/pnpm-workspace.yaml" <<'YAML'
packages:
  - apps/*
YAML
cat > "$WORK/nest-repo/apps/api/package.json" <<'JSON'
{
  "name":"@generic/api",
  "private":true,
  "dependencies":{"@nestjs/common":"^11.0.0","@nestjs/core":"^11.0.0"}
}
JSON
cat > "$WORK/nest-repo/apps/api/tsconfig.json" <<'JSON'
{"compilerOptions":{"experimentalDecorators":true}}
JSON
cat > "$WORK/nest-repo/apps/api/src/main.ts" <<'TYPESCRIPT'
import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';

const API_PREFIX = 'api/v1';
async function bootstrap() {
  const app = await NestFactory.create(class AppModule {});
  app.setGlobalPrefix(API_PREFIX);
  app.useGlobalPipes(new ValidationPipe({ transform: true }));
}
void bootstrap();
TYPESCRIPT
cat > "$WORK/nest-repo/apps/api/src/authenticated.decorator.ts" <<'TYPESCRIPT'
import { applyDecorators, UseGuards } from '@nestjs/common';

export function Authenticated() {
  return applyDecorators(UseGuards(class SyntheticGuard {}));
}
TYPESCRIPT
cat > "$WORK/nest-repo/apps/api/src/create-article.dto.ts" <<'TYPESCRIPT'
import { IsNotEmpty, MaxLength } from 'class-validator';

export class CreateArticleRequest {
  @IsNotEmpty()
  @MaxLength(80)
  name!: string;
}
TYPESCRIPT
cat > "$WORK/nest-repo/apps/api/src/article.controller.ts" <<'TYPESCRIPT'
import { Body, Controller, Get, Post } from '@nestjs/common';
import { Authenticated } from './authenticated.decorator';
import { CreateArticleRequest } from './create-article.dto';

@Controller('articles')
export class ArticleController {
  @Get()
  @Authenticated()
  list() { return []; }

  @Post()
  create(@Body() request: CreateArticleRequest) { return request; }
}
TYPESCRIPT
cat > "$WORK/nest-repo/apps/api/src/ignored.spec.ts" <<'TYPESCRIPT'
@Controller('must-not-be-discovered')
class IgnoredSpec {}
TYPESCRIPT

node "$DISCOVER" "$WORK/nest-repo" "$CONTRACT" > "$WORK/nest-inventory.json"
node "$DISCOVER" "$WORK/nest-repo" "$CONTRACT" > "$WORK/nest-inventory-second.json"
cmp -s "$WORK/nest-inventory.json" "$WORK/nest-inventory-second.json"
node - "$WORK/nest-inventory.json" <<'NODE'
const inventory=require(process.argv[2]);
if(inventory.profile!=='node-nestjs'){console.error(inventory);process.exit(1);}
const byTarget=new Map(inventory.surfaces.map((surface)=>[surface.target,surface.required_behaviors.join(',')]));
if(byTarget.get('GET /api/v1/articles (api)')!=='AUTH-FAIL,HAPPY'){console.error([...byTarget]);process.exit(1);}
if(byTarget.get('POST /api/v1/articles (api)')!=='HAPPY,VALIDATION-FAIL-NAME-MAX-LENGTH,VALIDATION-FAIL-NAME-NOT-EMPTY'){console.error([...byTarget]);process.exit(1);}
if(inventory.inputs.some((input)=>input.endsWith('ignored.spec.ts'))){console.error(inventory.inputs);process.exit(1);}
NODE

nest_fingerprint="$(node -e 'process.stdout.write(JSON.parse(require("node:fs").readFileSync(process.argv[1],"utf8")).source_fingerprint)' "$WORK/nest-inventory.json")"
cat > "$WORK/nest-catalog.md" <<'MARKDOWN'
<!-- AUTO-GENERATED by e2e-scenario-author. DO NOT EDIT. Human notes belong in docs/e2e-scenarios/notes.md. -->
<!-- Source fingerprint: sha256:NEST_FINGERPRINT -->
<!-- Contract: docs/e2e-scenarios/CONTRACT.md version 1 -->

# E2E Scenario Catalog

### `E2E-ARTICLE-GET-AUTH-FAIL` — 인증 없는 목록 조회는 거부된다

| Field | Value |
|---|---|
| Target | `GET /api/v1/articles (api)` |
| Purpose | 로컬 guard의 인증 실패 계약을 확인한다 |
| Preconditions | `service.api.ready == true` |
| Dataset | — |
| Expected | `401 Unauthorized` |
| Mutates | — |
| Depends-on | — |
| Captures | — |
| Notes | NestJS local auth floor |

```http
GET {{api}}/api/v1/articles
```

### `E2E-ARTICLE-GET-HAPPY` — 목록 조회는 성공한다

| Field | Value |
|---|---|
| Target | `GET /api/v1/articles (api)` |
| Purpose | 합성 사용자로 목록 조회 성공을 확인한다 |
| Preconditions | `service.api.ready == true` |
| Dataset | — |
| Expected | `200 OK`; response is an array |
| Mutates | — |
| Depends-on | — |
| Captures | — |
| Notes | NestJS controller route composition |

```http
GET {{api}}/api/v1/articles
Authorization: Bearer {{seed.API_AUTH_TOKEN}}
```

### `E2E-ARTICLE-POST-HAPPY` — 게시물 생성은 성공하고 정리된다

| Field | Value |
|---|---|
| Target | `POST /api/v1/articles (api)` |
| Purpose | 합성 이름으로 게시물 생성 성공을 확인한다 |
| Preconditions | `service.api.ready == true` |
| Dataset | `name=synthetic-article` |
| Expected | `201 Created`; `$.id` present |
| Mutates | `articles` |
| Depends-on | — |
| Captures | ARTICLE-ID |
| Notes | primary 결과와 무관하게 생성 게시물을 정리한다 |

```http
POST {{api}}/api/v1/articles
Content-Type: application/json

{"name":"synthetic-article"}

```

```shell
# teardown
curl -fsS -X DELETE "{{api}}/api/v1/articles/{{ARTICLE-ID}}"
```

### `E2E-ARTICLE-POST-VALIDATION-FAIL-NAME-MAX-LENGTH` — 긴 이름은 거부된다

| Field | Value |
|---|---|
| Target | `POST /api/v1/articles (api)` |
| Purpose | 이름의 MaxLength 제약을 확인한다 |
| Preconditions | `service.api.ready == true` |
| Dataset | `name=synthetic-over-limit` |
| Expected | `400 Bad Request`; `$.message` present |
| Mutates | — |
| Depends-on | — |
| Captures | — |
| Notes | NestJS class-validator floor |

```http
POST {{api}}/api/v1/articles
Content-Type: application/json

{"name":"synthetic-name-over-eighty-characters"}

```

### `E2E-ARTICLE-POST-VALIDATION-FAIL-NAME-NOT-EMPTY` — 빈 이름은 거부된다

| Field | Value |
|---|---|
| Target | `POST /api/v1/articles (api)` |
| Purpose | 이름의 IsNotEmpty 제약을 확인한다 |
| Preconditions | `service.api.ready == true` |
| Dataset | `name=blank` |
| Expected | `400 Bad Request`; `$.message` present |
| Mutates | — |
| Depends-on | — |
| Captures | — |
| Notes | NestJS class-validator floor |

```http
POST {{api}}/api/v1/articles
Content-Type: application/json

{"name":""}

```
MARKDOWN
sed "s/NEST_FINGERPRINT/$nest_fingerprint/" "$WORK/nest-catalog.md" > "$WORK/nest-catalog-bound.md"
node "$VALIDATOR" "$WORK/nest-catalog-bound.md" "$CONTRACT" "$WORK/nest-inventory.json" >/dev/null

sed 's/E2E-ARTICLE-POST-VALIDATION-FAIL-NAME-MAX-LENGTH/E2E-ARTICLE-POST-BOUNDARY/' \
  "$WORK/nest-catalog-bound.md" > "$WORK/nest-missing-coverage.md"
if node "$VALIDATOR" "$WORK/nest-missing-coverage.md" "$CONTRACT" "$WORK/nest-inventory.json" >/dev/null 2>&1; then
  echo 'NestJS catalog missing a source-required behavior was accepted' >&2
  exit 1
fi

node - "$WORK/nest-inventory.json" "$WORK/unknown-profile-inventory.json" <<'NODE'
const fs=require('node:fs');const inventory=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
inventory.profile='node-express';fs.writeFileSync(process.argv[3],JSON.stringify(inventory));
NODE
if node "$VALIDATOR" "$WORK/nest-catalog-bound.md" "$CONTRACT" "$WORK/unknown-profile-inventory.json" >/dev/null 2>&1; then
  echo 'unknown inventory profile was accepted' >&2
  exit 1
fi

cat > "$WORK/nest-repo/apps/api/src/duplicate.controller.ts" <<'TYPESCRIPT'
import { Controller, Get } from '@nestjs/common';

@Controller('articles')
export class DuplicateController {
  @Get()
  listAgain() { return []; }
}
TYPESCRIPT
if node "$DISCOVER" "$WORK/nest-repo" "$CONTRACT" >/dev/null 2>&1; then
  echo 'duplicate NestJS target was accepted' >&2
  exit 1
fi

mkdir -p "$WORK/unsupported-repo/src"
cat > "$WORK/unsupported-repo/package.json" <<'JSON'
{"name":"plain-node","private":true}
JSON
cat > "$WORK/unsupported-repo/src/index.ts" <<'TYPESCRIPT'
export const value = 1;
TYPESCRIPT
if node "$DISCOVER" "$WORK/unsupported-repo" "$CONTRACT" >/dev/null 2>&1; then
  echo 'unsupported Node repository profile was accepted' >&2
  exit 1
fi

grep -Fq '`node-nestjs`' "$SKILL"
grep -Fq 'Spring Boot or NestJS modules' "$RUNNER"
grep -Fq 'pnpm --filter <package> run start' "$REPO_ROOT/skills/e2e-runner/reference/kb/ci-integration.md"

if ! node --test "$ROOT/tests/dto-resolution.test.js" "$ROOT/tests/method-parameters.test.js" > "$WORK/dto-resolution.log" 2>&1; then
  cat "$WORK/dto-resolution.log" >&2
  exit 1
fi

printf '{"semantic_ac_key":"e2e_scenario_author_contract","outcome":"pass","bundled_contract":true,"catalog_validator":true,"primary_plus_teardown":true,"write_scope_consistent":true,"profile_detection":true,"spring_jvm_profile":true,"node_nestjs_profile":true,"node_nestjs_inventory_bound":true,"unknown_profile_rejected":true,"nestjs_global_prefix":true,"nestjs_validation_metadata":true,"nestjs_local_auth":true,"deterministic_inventory":true,"dynamic_runner_modules":true,"canonical_target_grammar":true,"duplicate_and_cycle_rejected":true,"undeclared_mutation_rejected":true,"shell_control_rejected":true,"teardown_reference_bound":true,"mutating_cte_rejected":true,"source_inventory_bound":true,"request_dto_constraints_discovered":true,"constant_and_property_paths_resolved":true,"composed_mapping_discovered":true,"project_auth_annotation_discovered":true,"kafka_dlq_discovered":true,"outbox_publish_consume_discovered":true,"source_coverage_required":true,"stale_fingerprint_rejected":true}\n'
